/**
 * @johnqh/lib - Shared utilities and common functions for 0xmail.box projects
 */

// Business Logic - Core business operations and enums (Goal 4)
export * from './business';

// Dependency Injection - All DI types and interfaces from local di module
export type {
  AdvancedPlatformStorage,
  AnalyticsClient,
  AnalyticsConfig,
  AnalyticsContextProvider,
  AnalyticsEventData,
  AnalyticsEventProperties,
  // Analytics types
  AnalyticsService,
  AppConfig,
  EnvironmentVariables,
  // Environment types
  EnvProvider,
  LocationHook,
  NavigationConfig,
  NavigationHook,
  NavigationOptions,
  // Navigation types
  NavigationService,
  NavigationState,
  // Network types
  NetworkClient,
  NetworkResponse,
  NetworkRequestOptions,
  NotificationCapabilities,
  NotificationClient,
  NotificationConfig,
  NotificationContextProvider,
  NotificationOptions,
  NotificationPermissionResult,
  NotificationResult,
  // Notification types
  NotificationService,
  // Storage types
  PlatformStorage,
  SerializedStorageService,
  StorageProvider,
  StorageService,
} from './di';

// Re-export enums from local di module
export { WalletType, StorageType, NetworkError } from './di';

// Re-export ALL exports from @johnqh/types as named exports
export {
  // Constants
  ANIMATION,
  API_BASE_URL,
  API_RETRY_ATTEMPTS,
  API_RETRY_DELAY,
  API_TIMEOUT,
  AUTH_STATUS,
  CHAIN_TYPE,
  CLAIM_PERIOD_DAYS,
  DEFAULT_NETWORKS,
  DEFAULT_RPC_ENDPOINTS,
  EMAIL_CONFIG,
  ERROR_MESSAGES,
  EVM_CHAIN_IDS,
  EVM_USDC_ADDRESSES,
  EXTERNAL_LINKS,
  NETWORK_IDENTIFIERS,
  NETWORK_IDS,
  PROTOCOL_CONSTANTS,
  ROUTES,
  SOLANA_CHAIN_IDS,
  SOLANA_USDC_MINTS,
  STATUS_VALUES,
  STORAGE_KEYS,
  SUBSCRIPTION_TIERS,
  SUCCESS_MESSAGES,
  TIME_FORMAT,
  USDC_DECIMALS,
  WALLET_NAMES,
  Z_INDEX,

  // Types and Enums
  AddressType,
  AnalyticsEvent,
  AnalyticsEventBuilder,
  AuthStatus,
  ChainType,
  ConnectionState,
  ConnectionType,
  Currency,
  EmailAction,
  EmailAddressType,
  EmailComposeType,
  EmailFolderUtils,
  EmailSortCriteria,
  EmailValidationState,
  ErrorType,
  FeatureFlag,
  FontSize,
  LogLevel,
  MailboxType,
  MediumView,
  MessageType,
  MobileView,
  NetworkError as NetworkErrorType,
  NotificationType,
  PlatformType,
  RequestStatus,
  SortOrder,
  StorageType as StorageTypeEnum,
  SubscriptionAction,
  Theme,
  TransactionStatus,
  WalletType as WalletTypeEnum,
  Web3UsernameValidator,

  // Utility types
  Optional,

  // Business interfaces
  Email,
  EmailFolder,
  Folder,
  MailBox,

  // Utility functions
  addDays,
  addHours,
  apiLogger,
  authLogger,
  canAccessProtectedFeatures,
  capitalize,
  contractLogger,
  createAssertion,
  createAuthenticateRequest,
  createChainStatsId,
  createCreateMailboxRequest,
  createDelegationId,
  createMultiChainId,
  createPaginationRequest,
  createPreAuthRequest,
  createSearchParams,
  createSubmitMessageRequest,
  createURLSearchParams,
  createUserMultiChainId,
  createValidator,
  ensLogger,
  escapeHtml,
  extractNonceFromMessage,
  formatBigInt,
  formatBytes,
  formatEmailDate,
  formatNumber,
  formatRelativeTime,
  formatTimestamp,
  formatUSDC,
  formatWalletAddress,
  generateAuthMessage,
  generateNonce,
  getAddressType,
  getAllChainIds,
  getAllEVMChainIds,
  getAllSolanaChainIds,
  getAuthStatusText,
  getChainDisplayName,
  getDefaultRPCEndpoint,
  getEVMChainId,
  getEVMUSDCAddress,
  getInitials,
  getSolanaUSDCMint,
  getWalletConnectionState,
  hasRequiredProperties,
  isApiResponse,
  isArray,
  isAuthExpired,
  isAuthStatusConnected,
  isBlank,
  isBoolean,
  isDateInRange,
  isDelegationResponse,
  isDelegatorsResponse,
  isENSName,
  isEVMChainId,
  isEVMNetwork,
  isEVMResponse,
  isEmail,
  isEmailAccountsResponse,
  isEntitlementResponse,
  isErrorResponse,
  isEvmAddress,
  isEvmRecipient,
  isIndexerErrorResponse,
  isIndexerSuccessResponse,
  isLeaderboardResponse,
  isMailboxErrorResponse,
  isNonceResponse,
  isNotBlank,
  isNullish,
  isNumber,
  isObject,
  isPointsResponse,
  isSNSName,
  isSignatureVerificationResponse,
  isSimpleMessageResponse,
  isSiteStatsResponse,
  isSolanaAddress,
  isSolanaChainId,
  isSolanaNetwork,
  isSolanaRecipient,
  isSolanaResponse,
  isSolanaSetupResponse,
  isSolanaStatusResponse,
  isSolanaTestTransactionResponse,
  isSolanaWebhookResponse,
  isString,
  isSuccessResponse,
  isTestNet,
  isUrl,
  isValidDate,
  isValidNonce,
  isValidSignature,
  isValidWalletAddress,
  isValidationResponse,
  isWalletConnected,
  isWalletVerified,
  isWildDuckRequest,
  isZeroAddress,
  logger,
  normalizeAddress,
  normalizeWhitespace,
  optional,
  parseDate,
  parseEmailAddress,
  parseJson,
  parseSearchParams,
  parseUSDC,
  pluralize,
  randomString,
  searchParamsToString,
  storageLogger,
  stripHtml,
  toCamelCase,
  toKebabCase,
  toSnakeCase,
  toTitleCase,
  truncate,
  validateAddress,
  validateAmount,
  validateArray,
  validateDomain,
  validateEventArgs,
  validateMessage,
} from '@johnqh/types';

// Re-export from @johnqh/mail_box_contracts as named exports
export {
  OnchainMailerClient,
  WalletDetector,
} from '@johnqh/mail_box_contracts';

// Infrastructure - Network clients only
export * from './network';

// Utilities - General utility functions
export * from './utils';

// Types - Selective exports to avoid conflicts (Goal 1)
// Export main email/API types but let business logic take precedence for enums
export {
  ApiClientConfig,
  // Error types
  ApiError,
  // Configuration types
  ApiInterceptor,
  ApiResponse,
  AuthenticationError,
  ChainInfo,
  // UI types
  DocSection,
  EmailListOptions,
  // Service interface types (email and persistence only)
  EmailService,
  GraphQLPaginationInput,
  GraphQLResponse,
  GraphQLWhereInput,
  IndexerCampaign,
  IndexerCampaignsResponse,
  IndexerCampaignStatsResponse,
  IndexerDelegatedToResponse,
  IndexerDelegation,
  IndexerDelegationResponse,
  IndexerEarnMethod,
  IndexerEmailAddress,
  IndexerEmailResponse,
  IndexerEntitlementResponse,
  IndexerHowToEarnResponse,
  IndexerLeaderboardEntry,
  IndexerLeaderboardResponse,
  IndexerMail,
  IndexerMessageResponse,
  IndexerNonceResponse,
  IndexerPointsHistoryEntry,
  IndexerPointsHistoryResponse,
  IndexerPointsSummary,
  IndexerPointsSummaryResponse,
  IndexerPreparedMail,
  IndexerPromoCodeResponse,
  IndexerPromoValidationResponse,
  IndexerPublicStatsResponse,
  IndexerRefereeLoginResponse,
  IndexerReferralResponse,
  IndexerSignatureRequest,
  IndexerSignatureVerification,
  isGraphQLResponse,
  isIndexerEmailResponse,
  // Type guards and validators
  isWildDuckAuthResponse,
  isWildDuckMessage,
  Mailbox,
  MailboxService,
  MockDataProvider,
  PaginationParams,
  PaginationResponse,
  PersistenceOptions,
  PersistenceResult,
  PersistenceService,
  StorageInfo,
  validateEmailAddress,
  validateObjectId,
  validateWalletAddress,
  ValidationError,
  WildDuckAddress,
  WildDuckAddressResponse,
  // API types
  WildDuckAuthRequest,
  WildDuckAuthResponse,
  WildDuckCreateMailboxRequest,
  WildDuckCreateUserRequest,
  WildDuckMessageAddress,
  WildDuckMessageAttachment,
  WildDuckMessageBase,
  WildDuckMessageDetail,
  WildDuckPreAuthRequest,
  WildDuckPreAuthResponse,
  WildDuckSendMessageRequest,
  WildDuckUpdateUserRequest,
  WildDuckUser,
  WildDuckUserResponse,
} from './types';

// Local business types with extensions
export { WalletUserData, User, EmailAddress } from './types/email';
export { WalletEmailAccounts } from '@johnqh/types';
